### ISSUE TITLE
Deprecate old library

### ISSUE THREAD

**Issue by sww314** [huvrdata/huvr-client#11]
Need new library that is compatible with current APIs

**Comment by david-wolgemuth** [comment]
handled by:

----

Pull requests list

https://github.com/huvrdata/huvr-client/pull/17
#17 by [david-wolgemuth](https://github.com/huvrdata/huvr-client/issues?q=is%3Apr+author%3Adavid-wolgemuth) was merged 2 minutes ago

https://github.com/huvrdata/huvr-client/pull/16
#16 by [david-wolgemuth](https://github.com/huvrdata/huvr-client/issues?q=is%3Apr+author%3Adavid-wolgemuth) was merged 18 hours ago

https://github.com/huvrdata/huvr-client/pull/15
#15 by [david-wolgemuth](https://github.com/huvrdata/huvr-client/issues?q=is%3Apr+author%3Adavid-wolgemuth) was merged 18 hours ago

https://github.com/huvrdata/huvr-client/pull/14
#14 by [david-wolgemuth](https://github.com/huvrdata/huvr-client/issues?q=is%3Apr+author%3Adavid-wolgemuth) was merged 18 hours ago

https://github.com/huvrdata/huvr-client/pull/13

**Comment by david-wolgemuth** [comment]
@huvrdata/dev - released new version of the client https://pypi.org/project/huvr-client/
